### ISSUE TITLE
error esphome

### ISSUE THREAD

**Issue by angeltonio** [esphome/esphome-vscode#11]
I have hassio on docker with ubuntu, and I install vscode addos, work fine with the Home Assistant Config Helper, but with esphome I have problems, because esphome show me a error constantly, like 

Cannot connect to ESPHome dashboard. Make sure you can access to ${this.endPoint} and have set option 'leave_front_door_open': true

I put that configuration on Esphome addos config, but always it´s the same.

And In myy Esphome Config Extensions on VsCode I have On dashboard Uri: addon_15ef4d2f_esphome:6052
and Validator: Dashboard but error all time...help me please..

**Comment by glmnet** [comment]
it will not work on port 6052

see readme it says:

> Use the ESPHome Dashboard, this can be the ESPHome running in Hass.io, in that case you will need to configure the add on to 'leave the front door open' and also give a tcp port in the addon for external access (in case you are only accessing via Ingress).

try giving another port like 8088

you will have to restart it.
You know you get it right when from your browser accessing:
`http://x.x.x.x:8088/vscode` give you a legend saying: 

_Can "Upgrade" only to "WebSocket"._

**Comment by glmnet** [comment]
I don't know why I wrote that, it does work on port 6052
Sorry for that, in any case, please open another issue
