### ISSUE TITLE
unknown tag <!secret>YAML

### ISSUE THREAD

**Issue by foxsam21** [esphome/esphome-vscode#16]
When using tag `!secret` the esphome plugin gives an error even though there is nothing wrong. It still compiles and works just that it shows up as an error.
![Selection_036](https://user-images.githubusercontent.com/11862524/103232169-c003b800-4907-11eb-8ccf-c51b5c6ffd33.png)

**Comment by glmnet** [comment]
which error is displayed? that should work just right, make sure you don't have another yaml validator active

**Comment by foxsam21** [comment]
the text_tip error says `unknown tag <!secret>YAML` there is no error compiling just the context error.

**Comment by glmnet** [comment]
ahh yes that will show as an error if you have the [yaml validator](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml)
The best way to avoid it in my experience is to disable the extension, you can do it just for "current workspace" so you can keep using elsewhere.
There is another way to avoid this error which is configuring that extension to avoid validating this custom tag, however right now this extension does not add any good validation info better than what ESPHome already does.

**Comment by kariudo** [comment]
I don't personally use esphome; however, this was a top result for the error that other people might have which can be better resolved without disabling the validator:

Just include the following in your vscode `settings.json`:
```json
  "yaml.customTags": [
    "!secret",
    "!include_dir_merge_named"
  ],
  ```

**Comment by Salvora** [comment]
I am also getting these errors but a little different.
```yaml
wifi:
  ssid: !secret esp_wifi_ssid
  password: !secret esp_wifi_pass
```
Secret 'esp_wifi_ssid' not defined

Any smart way to fix this without disabling the yaml extension?

**Comment by glmnet** [comment]
> I am also getting these errors but a little different.
> 
> ```yaml
> 
> wifi:
> 
>   ssid: !secret esp_wifi_ssid
> 
>   password: !secret esp_wifi_pass
> 
> ```
> 
> Secret 'esp_wifi_ssid' not defined
> 
> 
> 
> Any smart way to fix this without disabling the yaml extension?

Create a new issue. Explain properly your case
