### ISSUE TITLE
incorrect code validation error for substitutions

### ISSUE THREAD

**Issue by GrKoR** [esphome/esphome-vscode#19]
first.yaml

> substitutions:
>   devicename: boo
> 
> <<: !include common.yaml

common.yaml

> esphome:
>   name: $devicename
>   platform: ESP8266
> ...
> etc
> ...

It reports for string "name: $devicename" that "$" is incorrect symbol for name.
But it's ok and no problems with compilation

**Comment by glmnet** [comment]
thats an issue in ESPHome itself as validation is done by ESPHome.

I believe the issue has been solve in ESPHome already.

Thanks
