### ISSUE TITLE
Can't seem to make it work at all

### ISSUE THREAD

**Issue by glyndon** [esphome/esphome-vscode#23]
I hate to ask such a novice question here, since it's clear that the extension does work and I'm overlooking some prerequisite or other step, but:

I've tried installing the extension a few times, and have never seen any of its intended results. No validation, etc.
My esphome instance is local (/usr/local/bin/esphome), version 1.17.2;  VSCode 1.45.1
VSCode workspace includes a directory with all my .yaml files. They all compile cleanly and are running in production.
But if I open one in VSCode to edit, the extension doesn't seem to be active.

I've confirmed the extension settings are for a local instance, and even tried setting the path to esphome in the URI field.

Any suggestions as to what I'm doing incorrectly, I'll be grateful for.

**Comment by glmnet** [comment]
Make sure esphome is shown at the bottom right as language instead of YAML. not sure if docs explains that

**Comment by glyndon** [comment]
I saw in the code (not the docs) that it expects that to be set, but doing
so didn't seem to make any difference.

--
  Gary Dobbins

**Comment by glmnet** [comment]
Do you see any output in the output tab select ESPHome language server

**Comment by glyndon** [comment]
Yes, I do:
`The language client requires VS Code version ^1.52.0 but received version 1.45.1`

I am using VScode supplied by the OS distro (Ubuntu 20.10 at the moment).

**Comment by glmnet** [comment]
Ahh that makes sense then, yes.. you'll need to update, as it's linux I'm not sure how that works.

**Comment by glyndon** [comment]
Works now! (now that I've updated to the latest VSCode).
Thanks!

**Comment by glyndon** [comment]
Works now! (now that I've updated to the latest VSCode).
Thanks!
