### ISSUE TITLE
"/bin/sh: esphome not found" error

### ISSUE THREAD

**Issue by tracestep** [esphome/esphome-vscode#24]
I have esphome installed on my home directory at ~/.local/bin/esphome; Even though ~/.local/bin is on my $PATH, the extension does not find my local esphome to validate the yaml file. It is correctly configured for local validation.

Workaround: create a symlink from ~/.local/bin/esphome to /usr/local/bin/esphome.

Otherwise, great extension, by the way!

**Comment by ianchi** [comment]
same problem here.
In my case it is installed in ~/miniconda3/bin/esphome and it is in my path.
It works correctly when called from a terminal

**Comment by hooliowobbits** [comment]
> same problem here.
> In my case it is installed in ~/miniconda3/bin/esphome and it is in my path.
> It works correctly when called from a terminal

+1

the symlink also works, but it kinda defeats the purpose of having the python environment.
