### ISSUE TITLE
non yaml required files

### ISSUE THREAD

**Issue by glmnet** [esphome/esphome-vscode#3]
Looks like some kind of validation like "file exists" is being done for files in e.g. 
```
esphome:
  includes:
     path1
````

and also in e.g. `font:`

I'm not aware right now of other dependencies like this.
In case this is just a file exists validation may be another request type can be send, I mean `check_file_exists` instead of `read_file`

**Comment by OttoWinter** [comment]
Ah yes, true.

You can find the check here:

https://github.com/esphome/esphome/blob/7ad593d674e488e3abbfb3208326e3cbcd404d24/esphome/config_validation.py#L1023-L1044

So yes, I think we could add a check there for `CORE.vscode` that then does something similar to the `read_config_file` function here:

https://github.com/esphome/esphome/blob/a1a74488687b02ef2ac0ab57f6058d4aded402f3/esphome/config_helpers.py#L11

The modified file/directory function would, when in remote mode, print() to stdout a check_file_exists (and check_directory_exists) and wait for the result.
