### ISSUE TITLE
Need sync shema to last version ESPHome

### ISSUE THREAD

**Issue by olegrm** [esphome/esphome-vscode#37]
When the edit configuration does not find options, sample:
[contrast] is an invalid option for [display.ssd1306_i2c]. Please check the indentation.

**Comment by glmnet** [comment]
Well yes. I did some
Work on that already but esp idf support in ESPHome is a big change which broke several things I've made and now to support this I need  more time to work on this. 

Thanks for the request anyway!

**Comment by glmnet** [comment]
Schema is updated in v2.0.0
