### ISSUE TITLE
unable to find the extension in vs code

### ISSUE THREAD

**Issue by raidnet-ms** [esphome/esphome-vscode#40]
for some reason, after uninstalling the extension, I'm unable to find it again in the extension list.
If I search for esphome I do not get any result so I can't install it back.
Did this happen to anybody else?

**Comment by glmnet** [comment]
Have you find it? V2.0 is available now

**Comment by raidnet-ms** [comment]
Hi @glmnet ,
I have two different environments where HA os is running. Both run on similar hardware, rasp pi4.
One of them has no problems, the extension is running properly, while on the other one the extension disappeared and I don't find a way to get it back.
I can't even find it on the marketplace to install it again so I don't know how to get it back (neiter i know why it is missing).
I run only official integrations and addons.

**Comment by raidnet-ms** [comment]
Oh great, the v.2 is working. thank you very much!
