### ISSUE TITLE
Unknown tag !lambda

### ISSUE THREAD

**Issue by Plazmin** [esphome/esphome-vscode#46]
```YAML
on_raw_value:
      then:
        - text_sensor.template.publish:
            id: ${device}_uptime_human
            state: !lambda |-
              int seconds = round(id(${device}_uptime).raw_state);
              seconds = seconds % (24 * 3600);
              int days = seconds / (24 * 3600);
              int hours = seconds / 3600;
              if (days || hours)
                return {((days ? to_string(days)+"d " : "")+(hours ? to_string(hours)+"h" : "")).c_str()};
              else 
                return {"< 1hour"};
```

![11](https://user-images.githubusercontent.com/62091912/170955417-a0012664-d49b-4b17-93ea-d04331e56b2e.png)

Studio Code Server version: 5.0.4,  ESPHome version: 2022.5.1 I don't know if the bug was in earlier versions. The code compiles without any problems.

The validation applies to the file esphome/common/common.yaml. No problem when the file is in the esphome directory.

**Comment by glmnet** [comment]
Are you sure the language selected at bottom right is ESPHome and not home assistant?

**Comment by Plazmin** [comment]
You were right. I corrected it, changed it to esphome and it works now. Thank you for your help.
