### ISSUE TITLE
Extension doesn't work on VSCode 1.68

### ISSUE THREAD

**Issue by definitio** [esphome/esphome-vscode#47]
```
Configuring ESPHome with local validation...
Using local ESPHome
yaml.hover.error
yaml.hover.error
yaml.hover.error
```

**Comment by glmnet** [comment]
It's working here with v2022.5.1 of the extension, which version are you using?

Can you share more details? may be a screenshot, thanks

**Comment by definitio** [comment]
Sorry for late answer. Completion and hover doesn't work. I use [The Open Source build of Visual Studio Code](https://archlinux.org/packages/community/x86_64/code/).
```
Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-16T08:22:04.269Z
Electron: 17.4.3
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.18.5-zen1-1-zen

ESPHome v2022.6.1
```
![Screenshot_20220620_192515](https://user-images.githubusercontent.com/37266727/174645359-161a329a-1e54-4fac-8700-8fbe756bcf59.png)

**Comment by glmnet** [comment]
Ahhh didn't try with other versions. I know it works on the embedded vscode that is included in HA community addons
