### ISSUE TITLE
!secret syntactic error

### ISSUE THREAD

**Issue by CharlyAutomatico** [esphome/esphome-vscode#53]
Hi,
These lines are given me some syntactic error into vscode when using a separated yaml file for paswords (secrets.yaml)

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

How can I figure out this behavior
thanks

**Comment by glmnet** [comment]
Can you provide a screenshot?

**Comment by CharlyAutomatico** [comment]
Yes, off course
<img width="751" alt="Captura de pantalla 2022-09-04 a las 21 02 35" src="https://user-images.githubusercontent.com/64072797/188329460-5d7e1ab8-cabc-4b59-910d-3afc9b091fc2.png">

**Comment by glmnet** [comment]
Can you check at bottom right of the screen you have selected ESPHome as the "language"?

**Comment by CharlyAutomatico** [comment]
Glup, what a shame!, you were 200% right
Sorry
