### ISSUE TITLE
New Climate 'Preset' options 

### ISSUE THREAD

**Issue by 3ative** [esphome/esphome-vscode#63]
I guess coz it's 'new' there needs to be time before VS Code gets updated too.

Opening issue just in case. 💖

 E.G.:
 
 
![image](https://user-images.githubusercontent.com/51385971/196757943-8db7f838-92d5-4868-b827-d69e3f809bc4.png)

**Comment by 3ative** [comment]
Hmmm I may have posted this in wrong tracker - Example shown is from HA's VS Code Add-on.

**Comment by glmnet** [comment]
Indeed

I don't know if you can install latest version (just published) in the HA's add on or a push is needed on that repo

**Comment by 3ative** [comment]
Cool, thank... I'll wait. Cheers.
