### ISSUE TITLE
Yaml extension conflict

### ISSUE THREAD

**Issue by borpin** [esphome/esphome-vscode#7]
There may be a simple solution to this, but as my ESPHome files sit under my Home Assistant config folder, VSCode is using the HA extension rather than the ESPHome extension.

Can you specify an extension to be used for a specific folder location within a workspace, or could there be an opening comment in the file to force the ESPHome extension?

Great idea.

**Comment by borpin** [comment]
So re-read the docs - I need dashboard mode (hassio)

![image](https://user-images.githubusercontent.com/1322749/68053872-ebc7e580-fce4-11e9-8643-eb6454bfd0d3.png)

Should the uri, be one that works from a browser? If I load the dashboard I use `<IP>/hassio/ingress/15ef4d2f_esphome`.

**Comment by OttoWinter** [comment]
@borpin I don't think it will work with Hass.io ingress (that uses a different auth system).

CC: @glmnet 

As for the original question: I don't think that's really possible - maybe VSCode has some options where you can configure a workspace folder to use a specific language-server for file types, but @glmnet probably knows more about that.

**Comment by glmnet** [comment]
One solution for you might be opening another VSCode window directly at were the ESPHome files are, then you can go to extensions and disable the HomeAssistant extension for the workspace, I hope vscode will create a .vscode folder inside ESPHome folder to configure the workspace.

**Comment by glmnet** [comment]
Right now plugin version 0.1.0 is compatible with ESPHome v1.13 and next version will be compatible with 1.14 once it is released

The url there looks ok, the hassio one will not work as it will need authentication and it is not yet implemented.

You must be able to reach the ESPHome dashboard by entering the same uri location on your web browser. i.e. you should be at ESPHome dashboard with `<ip>:6052`
You also should be on the dashboard home page directly, not at the login page.

**Comment by glmnet** [comment]
Ohhh v1.14 is released.... you'll need to wait for me to push 0.2.0 ... hold on
