### ISSUE TITLE
unknown tag <!lambda> when lambda used to return a value

### ISSUE THREAD

**Issue by marcoaddario** [esphome/esphome-vscode#73]
the !lambda syntax is not recognised when used to return a value
<img width="914" alt="image" src="https://user-images.githubusercontent.com/3762730/222115071-da3c0000-61da-4535-a8b2-839f600825d8.png">

while it is recognized (and accepted) by the ESPHome integrated editor

The code is recognized as ESPHome (and not home assistant ;-) )

VSCode version:  1.75.1 
ESPhome plugin version: v2022.11.0

**Comment by glmnet** [comment]
Is anybody able to reproduce this?
I cannot:

![image](https://user-images.githubusercontent.com/96162/222197343-c745a971-1c3f-4fe7-8b65-0f4cac1db41b.png)
![image](https://user-images.githubusercontent.com/96162/222197629-a07ce102-cf4e-456b-b8ac-c301afeb6523.png)

**Comment by beausmith** [comment]
I'm getting same error `unknown tag <!lambda>YAML` 

VSCode version: 1.85.1
VSCode ESPhome extension version: v2023.9.0 - 2023-10-09
ESPhome Home Assistant AddOn version: 2023.11.6

<img width="1309" alt="image" src="https://github.com/esphome/esphome-vscode/assets/28444/0cf83031-f315-4a10-bfcc-92802638cf18">

**Comment by glmnet** [comment]
Do you have the redhat yaml extension installed? Try disabling it for the workspace

**Comment by mikesmitty** [comment]
If you want to keep the redhat yaml extension enabled you can add it as a custom tag in settings.json:
```
    "yaml.customTags": [
        "!lambda scalar"
    ]
```
https://github.com/redhat-developer/vscode-yaml/issues/669#issuecomment-1135687604
