### ISSUE TITLE
Schema generation error

### ISSUE THREAD

**Issue by grahambrown11** [esphome/esphome-vscode#79]
@glmnet the "newish" speaker component breaks the build scheme script:
https://github.com/esphome/esphome/blob/17fed954bf74a018f527b541dab2d30101169bb8/script/build_language_schema.py#L533
My quick fix was to add 
```
if x == "speaker.SPEAKER_SCHEMA":
    continue
```
But don't think that's a solution 😜, I am trying to get the new alarm_control_panel component to get the auto complete suggestions in the dashboard.

The VSCode script refers to`build_jsonschema.py` which seems to be replaced by `build_language_schema.py` but that is missing the `#!` & the execute flag so it doesn't run 😞 

All the `"docs"` attributes are removed after running `build_language_schema.py`

**Comment by glmnet** [comment]
Yes. I've already lost a battle against the speaker thing. 

The docs ara added to the json by another script which is in the docs repo. 

I might just push an schema update for the non conflicting components meanwhile. 

Thanks for giving it a try!

**Comment by grahambrown11** [comment]
So I fiddled and manually pulled out just the new component I created https://github.com/esphome/dashboard/pull/496 would be nice if this could be handled by an automated GitHub Action routine...

**Comment by jesserockz** [comment]
@glmnet I am happy to remove the base SPEAKER_SCHEMA as its really not needed? It can be added back later if something gets added into the common schema

**Comment by glmnet** [comment]
I was looking at it. Actually the oddity here is that the schema is empty, I didn't understand first hand why it was different. 

Let's keep it this way as it makes sense. 

I'll wait for this month release and push a full schema update. 

Thank you

**Comment by glmnet** [comment]
Close with #80
