### ISSUE TITLE
Possible to use with esphome via WSL?

### ISSUE THREAD

**Issue by lord-carlos** [esphome/esphome-vscode#8]
Hi

I use ESPhome through windows subsystem for linux (WSL)
Is it possible to get the plugin working through that?

Thanks

**Comment by OttoWinter** [comment]
You should be able to if you use it in dashboard mode.

CC: @glmnet

**Comment by glmnet** [comment]
Yes, Otto is right, as a general rule if you can see the dashboard from your browser you can use that method.

Another option is to use VSCode remote, make sure you have the wsl remote extension then on the wsl command prompt you can run

`vscode .`

then vs code should launch in the wsl on the folder your yaml files are, install the extension on the wsl and configure it to run local

The same remote can be used via a ssh remote, when esphome is installed remotely.

**Comment by lord-carlos** [comment]
Super, thank you.
