### ISSUE TITLE
hidden files arent picked up

### ISSUE THREAD

**Issue by kinghat** [esphome/esphome-vscode#84]
when hiding files from the dashboard that are used for yaml insertion via prepending a dot to the file name: https://esphome.io/guides/configuration-types.html#yaml-insertion-operator, the extension no longer picks up the file as its own:  even if "esphome" is also in the file name.

![image](https://github.com/esphome/esphome-vscode/assets/16073360/cdfb59c3-f10e-41ef-a9c8-ef457d895d2d)

**Comment by glmnet** [comment]
you mean, it does not auto selects ESPHome at bottom right?

**Comment by kinghat** [comment]
> you mean, it does not auto selects ESPHome at bottom right?

hey @glmnet! yep thats correct.

**Comment by glmnet** [comment]
is this the ESPHome inside the HA's Studio Code Server? In that case this might be relevant: https://github.com/hassio-addons/addon-vscode/blob/main/vscode/rootfs/root/.code-server/settings.json

May be the pattern in lines 4 and 5 aren't matching your setup. You can try fiddling with that, see this for more information https://stackoverflow.com/questions/29973619/how-to-associate-a-file-extension-with-a-certain-language-in-vs-code

If you find a setting working better for you, you might want to create an issue on that repo

I could not reproduce here though... 

![image](https://github.com/esphome/esphome-vscode/assets/96162/b2622f24-7887-48a5-8332-97b216d956e5)

**Comment by kinghat** [comment]
> is this the ESPHome inside the HA's Studio Code Server? In that case this might be relevant: https://github.com/hassio-addons/addon-vscode/blob/main/vscode/rootfs/root/.code-server/settings.json

this is through the vscode remote ssh extension.
