### ISSUE TITLE
Improve documentation to indicate importance of setting file type

### ISSUE THREAD

**Issue by thargy** [esphome/esphome-vscode#88]
I wonder if this is just my misunderstanding or a clash with other extensions, but I didn't get any of the plugin's functionality until I clicked the file type and changed it from 'YAML' to 'ESPHome'.  As it doesn't appear evident from the readme, could you add a note to indicate the importance of taking that step?

**Comment by glmnet** [comment]
Yes being new to vscode May be leads to this kind of issue. Not sure how to document this. 
May be other stuff like kubernetes which also uses yaml files are explaining this somehow?

R&D + PR welcome

**Comment by thargy** [comment]
Added PR as requested.
